project:
  type: website
  output-dir: docs

website:
  title: "Everyday ggplot2 extension 🫖"
  reader-mode: true
  repo-url: https://github.com/EvaMaeRey/everyday_ggplot2_extension
  repo-actions: [edit, issue]
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: tutorials.qmd
        text: Tutorials
      - href: community.qmd
        text: Community
      - href: cookbook.qmd
        text: Cookbook

    tools:
      - icon: github
        href: https://github.com/evamaerey/everyday_ggplot2_extension
  page-footer:
    right: "Built with [Quarto](https://quarto.org/)"
    left: "&copy; Copyright 2023, Gina Reynolds"

format:
  html:
    theme: theme.scss
    toc: true

editor: source
